In [4]:
import numpy as np
import pandas as pd

In [7]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([1,2,3])
d = {'a':10,'b':20,'c':30}

In [8]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(my_list, index = labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr)

0    1
1    2
2    3
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
data = {
    'Name' : ['John','Doe','Kartik','Deepika'],
    'Age' : [24,12,15,17],
    'City' : ['New york','India','Berlin','London'],
    'Salary' : [26000, 65000, 75000, 100000]
}

df = pd.DataFrame(data)

In [13]:
df

      Name  Age      City  Salary
0     John   24  New york   26000
1      Doe   12     India   65000
2   Kartik   15    Berlin   75000
3  Deepika   17    London  100000

In [14]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name","Age","Country","Salary"]
df2 = pd.DataFrame(data_list, columns= columns)
df2

    Name  Age   Country  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2[["Name","Country"]]

    Name   Country
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [17]:
df2["Destination"] = ["Doctor","Engineer","Doctor","Engineer"]

In [18]:
df2

    Name  Age   Country  Salary Destination
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [22]:
df2.drop(3,axis=0)
df2

    Name  Age   Country  Salary Destination
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [23]:
df2.loc[[0,1]]

   Name  Age   Country  Salary Destination
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [28]:
df2.iloc[3]

Name              Linda
Age                  42
Country          London
Salary            85000
Destination    Engineer
Name: 3, dtype: object

In [29]:
df2.loc[[0,1]][["Name","Country"]]

   Name   Country
0  John  New York
1  Anna     Paris

In [32]:
df2[df2["Age"] > 30]

    Name  Age Country  Salary Destination
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [35]:
df2[(df2["Age"] > 30) & (df2["Country"] == "Paris")]

   Name  Age Country  Salary Destination
1  Anna   34   Paris   70000    Engineer